version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=cloudlogger@123
      - POSTGRES_USER=root
      - POSTGRES_DB=cloud_logger
volumes:
  postgres-data:
